DROP TABLE IF EXISTS rival;
DROP TABLE IF EXISTS escena;
DROP TABLE IF EXISTS protagoniza;
DROP TABLE IF EXISTS superheroe;
DROP TABLE IF EXISTS persona_real;
DROP TABLE IF EXISTS villano;
DROP TABLE IF EXISTS pelicula;
